### ISSUE TITLE
Progress not rounded

### ISSUE THREAD

**Issue by rondog** [manumaticx/circularprogress#3]
Hey man! I'm developing an alloy app so I decided to give your widget a shot. I got it all working, but the progress seems to not really be circular like my original code. I went through your widget.js briefly and didn't notice anything specifically causing it. Do you have any ideas? 

I posted a screenshot below. Just a side note, I increased the progressWidth significantly to magnify the issue. Could it be a problem with my TSS?

``` CSS
'#progress' : {
    width:30,
    height:30,
    bottom:13,
  left:3,
  margin:2,
  backgroundColor:'#fff',
  progressColor:'#4ba818',
  progressBackgroundColor:'#333',
  progressWidth: 10,
  showText: true,
  color: '#333',
    font: {
        fontSize:10,
        fontFamily:Alloy.Globals.fontFamily
  }
}
```

![screen shot 2014-12-11 at 10 21 06 am](https://cloud.githubusercontent.com/assets/709057/5399404/d1fe026a-811f-11e4-92b2-e8c9ae5f7912.png)
